PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE doors(id integer unique, map text, tilex integer, tiley integer, tomap text, tox integer, toy integer);
INSERT INTO "doors" VALUES(0,'v_hamsford.txt',3,12,'v_hamsford_i.txt',3,13);
INSERT INTO "doors" VALUES(1,'v_hamsford_i.txt',3,13,'v_hamsford.txt',3,12);
INSERT INTO "doors" VALUES(2,'v_hamsford.txt',6,3,'v_hamsford_i.txt',NULL,NULL);
INSERT INTO "doors" VALUES(3,'v_hamsford.txt',9,4,'v_hamsford_i.txt',NULL,NULL);
INSERT INTO "doors" VALUES(4,'v_hamsford.txt',13,5,'v_hamsford_i.txt',NULL,NULL);
INSERT INTO "doors" VALUES(5,'v_hamsford.txt',5,8,'v_hamsford_i.txt',NULL,NULL);
INSERT INTO "doors" VALUES(6,'v_hamsford.txt',8,10,'v_hamsford_i.txt',NULL,NULL);
INSERT INTO "doors" VALUES(7,'v_hamsford.txt',13,10,'v_hamsford_i.txt',NULL,NULL);
INSERT INTO "doors" VALUES(8,'v_hamsford.txt',5,14,'v_hamsford_i.txt',NULL,NULL);
INSERT INTO "doors" VALUES(9,'v_hamsford.txt',10,14,'v_hamsford_i.txt',NULL,NULL);
INSERT INTO "doors" VALUES(10,'v_hamsford.txt',14,13,'v_hamsford_i.txt',NULL,NULL);
INSERT INTO "doors" VALUES(11,'v_hamsford_i.txt',6,2,'v_hamsford.txt',NULL,NULL);
INSERT INTO "doors" VALUES(12,'v_hamsford_i.txt',11,4,'v_hamsford.txt',NULL,NULL);
INSERT INTO "doors" VALUES(13,'v_hamsford_i.txt',12,5,'v_hamsford.txt',NULL,NULL);
INSERT INTO "doors" VALUES(14,'v_hamsford_i.txt',6,8,'v_hamsford.txt',NULL,NULL);
INSERT INTO "doors" VALUES(15,'v_hamsford_i.txt',7,10,'v_hamsford.txt',NULL,NULL);
INSERT INTO "doors" VALUES(16,'v_hamsford_i.txt',12,10,'v_hamsford.txt',NULL,NULL);
INSERT INTO "doors" VALUES(17,'v_hamsford_i.txt',3,13,'v_hamsford.txt',NULL,NULL);
INSERT INTO "doors" VALUES(18,'v_hamsford_i.txt',5,13,'v_hamsford.txt',NULL,NULL);
INSERT INTO "doors" VALUES(19,'v_hamsford_i.txt',10,13,'v_hamsford.txt',NULL,NULL);
INSERT INTO "doors" VALUES(20,'v_hamsford_i.txt',12,14,'v_hamsford.txt',NULL,NULL);
COMMIT;
